[package]
name = "expr"
version = "0.0.1"
authors = []
build = "../../mkmain.rs"

[lib]
name = "uu_expr"
path = "expr.rs"

[dependencies]
libc = "0.2.26"
onig = "3.0"
uucore = { path="../uucore" }

[[bin]]
name = "expr"
path = "../../uumain.rs"
