[package]
name = "basename"
version = "0.0.1"
authors = []
build = "../../mkmain.rs"

[lib]
name = "uu_basename"
path = "basename.rs"

[dependencies]
uucore = { path="../uucore" }
failure = "0.1.1"
failure_derive = "0.1.1"

[[bin]]
name = "basename"
path = "../../uumain.rs"
