[package]
name = "uu_wc"
version = "0.0.1"
authors = ["uutils developers"]
license = "MIT"
description = "wc ~ (uutils) display newline, word, and byte counts for input"

homepage = "https://github.com/uutils/coreutils"
repository = "https://github.com/uutils/coreutils/tree/master/src/uu/wc"
keywords = ["coreutils", "uutils", "cross-platform", "cli", "utility"]
categories = ["command-line-utilities"]
edition = "2018"

[lib]
path = "src/wc.rs"

[dependencies]
getopts = "0.2.18"
uucore = { version="0.0.4", package="uucore", path="../../uucore" }
uucore_procs = { version="0.0.4", package="uucore_procs", path="../../uucore/src/uucore_procs" }

[[bin]]
name = "wc"
path = "src/main.rs"
