language: rust
matrix:
  fast_finish: true
  include:
    - rust: stable
      os: linux
      env: FEATURES='' RUSTFLAGS='-C link-dead-code'
    - rust: stable
      os: osx
      env: FEATURES=''
    - rust: beta
      os: linux
      env: FEATURES=''
    - rust: beta
      os: osx
      env: FEATURES=''
    - rust: nightly
      os: linux
      env: FEATURES=nightly
    - rust: nightly
      os: osx
      env: FEATURES=nightly
    - rust: nightly
      os: linux
      env: FEATURES=nightly,redox CC=x86_64-unknown-redox-gcc CARGO_ARGS='--no-default-features --target=x86_64-unknown-redox' REDOX=1
  allow_failures:
    - rust: nightly
      os: linux
      env: FEATURES=nightly,redox CC=x86_64-unknown-redox-gcc CARGO_ARGS='--no-default-features --target=x86_64-unknown-redox' REDOX=1

cache:
  directories:
    - $HOME/.cargo

sudo: true

before_install:
  - if [ $REDOX ]; then ./.travis/redox-toolchain.sh; fi

script:
  - cargo build $CARGO_ARGS --features "$FEATURES"
  - if [ ! $REDOX ]; then cargo test $CARGO_ARGS --features "$FEATURES" --no-fail-fast; fi

addons:
  apt:
    packages:
      - libssl-dev
      - libcurl4-openssl-dev
      - libelf-dev
      - libdw-dev
      - cmake
      - binutils-dev
      - libiberty-dev

after_success: |
  if [ "$TRAVIS_OS_NAME" = linux -a "$TRAVIS_RUST_VERSION" = stable ]; then
    cargo install cargo-kcov
    bash <(cargo kcov --print-install-kcov-sh)
    cargo kcov
    bash <(curl -s https://codecov.io/bash) -f target/cov/kcov-merged/cobertura.xml
  fi

