[package]
name = "uu_printenv"
version = "0.0.1"
authors = ["uutils developers"]
license = "MIT"
description = "printenv ~ (uutils) display value of environment VAR"

homepage = "https://github.com/uutils/coreutils"
repository = "https://github.com/uutils/coreutils/tree/master/src/uu/printenv"
keywords = ["coreutils", "uutils", "cross-platform", "cli", "utility"]
categories = ["command-line-utilities"]
edition = "2018"

[lib]
path = "src/printenv.rs"

[dependencies]
getopts = "0.2.18"
uucore = { version="0.0.4", package="uucore", path="../../uucore" }
uucore_procs = { version="0.0.4", package="uucore_procs", path="../../uucore/src/uucore_procs" }

[[bin]]
name = "printenv"
path = "src/main.rs"
