[package]
name = "uu_factor"
version = "0.0.1"
authors = ["uutils developers"]
license = "MIT"
description = "factor ~ (uutils) display the prime factors of each NUMBER"

homepage = "https://github.com/uutils/coreutils"
repository = "https://github.com/uutils/coreutils/tree/master/src/uu/"
keywords = ["coreutils", "uutils", "cross-platform", "cli", "utility"]
categories = ["command-line-utilities"]
edition = "2018"

[lib]
path = "src/factor.rs"

[dependencies]
rand = "0.5"
uucore = { version="0.0.4", package="uucore", path="../../uucore" }
uucore_procs = { version="0.0.4", package="uucore_procs", path="../../uucore/src/uucore_procs" }

[[bin]]
name = "factor"
path = "src/main.rs"
